language: node_js

node_js:
  - "v12.19.0"
  - "v14.14.0"
  - "v15.0.1"

os:
  - linux
  - osx

cache:
  yarn: true
  directories:
    - node_modules

jobs:
  include:
    # Fix hanging Windows tests (because of yarn):
    # https://travis-ci.community/t/build-doesnt-finish-after-completing-tests/288
    - node_js: "v10.18.1"
      os: windows
      env: YARN_GPG=no
    - node_js: "v12.14.1"
      os: windows
      env: YARN_GPG=no
    - node_js: "v13.7.0"
      os: windows
      env: YARN_GPG=no

before_script:
  - npm link
script:
  - climax new app

branches:
  only:
    - develop
    - master

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f6c7fbd99c6425464bbc
    on_cancel: change
    on_error: always
    on_failure: always
    on_start: change
    on_success: change
