language: node_js

node_js:
  - "v10.18.1"
  - "v12.14.1"
  - "v13.7.0"

os:
  - linux
  - osx
  - windows

cache:
  yarn: true
  directories:
    - node_modules

before_script:
  - npm link
script:
  - climax new app

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f6c7fbd99c6425464bbc
    on_cancel: change
    on_error: always
    on_failure: always
    on_start: change
    on_success: change
